Version 1
net-5/bankaccount-MariusSimion79 pull request #1
Opened 2019-07-03 06:36 UTC by MariusSimion79

2019-07-04 06:56 UTC, irinascurtusiit requested changes

2019-07-04 06:56 UTC, irinascurtusiit commented on BankAccount/BankAccount/Account.cs
> +        public void MakeDeposit(decimal amount, DateTime date, string observation)
date de aici ar trebui sa fie automat asignat cand se face call-ul catre metoda, nu trebuie dat de mana, ci automatizat

2019-07-04 06:56 UTC, irinascurtusiit commented on BankAccount/BankAccount/Account.cs
> +        {
la fel si aici, referitor la date

2019-07-04 06:56 UTC, irinascurtusiit commented on BankAccount/BankAccount/Account.cs
> +            this.Owner = name;
Ownerul trebuie dat in constructor. In teorie nu poti avea bankaccount fara owner. Si facem clase ca sa pyutem refolosi functionalitate. Daca hardcodam chestii...nu le putem refolosi

2019-07-04 06:56 UTC, irinascurtusiit commented on BankAccount/BankAccount/Account.cs
> +        public Account(string name)
daca dai name...se intelege ca e name-ul accountului. Modifica te rog in ownerName or sth like this

2019-07-05 09:24 UTC, MariusSimion79 commented on BankAccount/BankAccount/Account.cs
> +        public void MakeDeposit(decimal amount, DateTime date, string observation)
done

2019-07-05 09:24 UTC, MariusSimion79 commented on BankAccount/BankAccount/Account.cs
> +        {
done

2019-07-05 09:30 UTC, MariusSimion79 commented on BankAccount/BankAccount/Account.cs
> +        public Account(string name)
done

2019-07-05 09:36 UTC, MariusSimion79 commented on BankAccount/BankAccount/Account.cs
> +            this.Owner = name;
Am modificat Owner in OwnerName si name in ownerName, pentru a elimina confuziile.

2019-07-06 11:29 UTC, merged